### PR TITLE
gc_max_lifetime => gc_maxlifetime

### PR DESCRIPTION
**Pull request by samayo**

### CODE REVIEW

**Comment by samayo** [comment]
I give up, plus I'm on mobile

**Comment by kelunik** [comment]
Arya still depends on Alert, Composer setup doesn't work... this needs really some work. :-(

**Comment by samayo** [comment]
Sorry :), But I think merging this would do no harm, as the issue here is clear, and the test break can be dealt separately.

**Comment by kelunik** [comment]
I think https://github.com/samayo/Arya/blob/master/lib/Sessions/Session.php#L34 should be the last missing fix.

**Comment by kelunik** [comment]
And no, I won't merge it with broken tests. ;-)

**Comment by kelunik** [comment]
Thanks!

**Pull request merged**
